### ISSUE TITLE
crush on a channel without a message

### ISSUE THREAD

**Issue by takameron** [PyYoshi/slack-dump#2]
Thank you for your convenient program.

On a channel without a message, it seems that it ends with an error `index out of memory`.

```
.
.
.
dump public channel
dump channel foo
dump channel bar
dump channel baz
panic: runtime error: index out of range

goroutine 1 [running]:
main.fetchChannelHistory(0xc0420fe0c0, 0xc04213c770, 0x9, 0xc04216ed60, 0x13, 0x6e0000006e)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:381 +0x408
main.dumpChannel(0xc0420fe0c0, 0xc0421e0000, 0x35, 0xc04213c770, 0x9, 0xc04213c780, 0xb, 0x7d64cb, 0x7)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:305 +0x142
main.dumpChannels(0xc0420fe0c0, 0xc0421e0000, 0x35, 0xc042082050, 0x0, 0x3, 0x0, 0x1, 0xc0423289a0)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:261 +0x23b
main.dumpRooms(0xc0420fe0c0, 0xc0421e0000, 0x35, 0xc042082050, 0x0, 0x3)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:205 +0xd7
main.main.func1(0xc0420aa840)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:100 +0x227
github.com/PyYoshi/slack-dump/vendor/github.com/urfave/cli.HandleAction(0x7485e0, 0x7ee470, 0xc0420aa840, 0xc04204c4e0, 0x0)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/vendor/github.com/urfave/cli/app.go:503 +0x83
github.com/PyYoshi/slack-dump/vendor/github.com/urfave/cli.(*App).Run(0xc042104000, 0xc042082000, 0x5, 0x8, 0x0, 0x0)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/vendor/github.com/urfave/cli/app.go:268 +0x613
main.main()
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:105 +0x330
```

**Comment by munierujp** [comment]
Maybe...🤔 

```go
messages := history.Messages
latest := messages[len(messages)-1].Timestamp
```

**Comment by PyYoshi** [comment]
Pull Request Welcome!
